import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Learn2UX",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-[#FDFDFD] min-h-screen w-full relative flex flex-col">
                <main className="flex-1">
                    <div className="container mx-auto">{children}</div>
                </main>
            </body>
        </html>
    );
}
